### ISSUE TITLE
Helvetica not found as resource

### ISSUE THREAD

**Issue by VagueGit** [DesignLiquido/RazorPDF2#1]
Stack Trace: 
[DocumentException: Helvetica not found as resource.]
   RazorPDF.Legacy.Text.Pdf.Type1Font..ctor(String afmFile, String enc, Boolean emb, Byte[] ttfAfm, Byte[] pfb, Boolean forceRead) +894
   RazorPDF.Legacy.Text.Pdf.BaseFont.CreateFont(String name, String encoding, Boolean embedded, Boolean cached, Byte[] ttfAfm, Byte[] pfb, Boolean noThrow, Boolean forceRead) +1056
   RazorPDF.Legacy.Text.Pdf.BaseFont.CreateFont(String name, String encoding, Boolean embedded, Boolean cached, Byte[] ttfAfm, Byte[] pfb, Boolean noThrow) +81
   RazorPDF.Legacy.Text.Pdf.BaseFont.CreateFont(String name, String encoding, Boolean embedded) +74
   RazorPDF.Legacy.Text.Font.GetCalculatedBaseFont(Boolean specialEncoding) +562
   RazorPDF.Legacy.Text.Chunk.GetWidthPoint() +136
   RazorPDF.Legacy.Text.ListItem.SetIndentationLeft(Single indentation, Boolean autoindent) +101
   RazorPDF.Legacy.Text.List.Add(Object o) +541
   RazorPDF.Legacy.Text.Html.SimpleParser.HTMLWorker.EndElement(String tag) +2525
   RazorPDF.Legacy.Text.Xml.SimpleParser.SimpleXMLParser.ProcessTag(Boolean start) +146
   RazorPDF.Legacy.Text.Xml.SimpleParser.SimpleXMLParser.Go(TextReader reader) +1920
   RazorPDF.Legacy.Text.Xml.SimpleParser.SimpleXMLParser.Parse(ISimpleXMLDocHandler doc, ISimpleXMLDocHandlerComment comment, TextReader r, Boolean html) +101
   RazorPDF.Legacy.Text.Html.SimpleParser.HTMLWorker.Parse(TextReader reader) +52
   RazorPDF.PdfView.Render(ViewContext viewContext, TextWriter writer) +373
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +291
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) +13
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +56
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +420
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +52
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +173
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9744373
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1073.0

This error occurred using Visual Studio 2015 ASP.Net 4.5.2, RazorPDF 2.0.0 calling PdfResult.

**Comment by VagueGit** [comment]
This error occurred using Visual Studio 2015 ASP.Net 4.5.2, RazorPDF 2.0.0

**Comment by ahmed-sherien** [comment]
I have the same issue ... is it fixed ?

**Comment by VagueGit** [comment]
@ahmed-sherien We couldn't get RazorPDF to work so we moved to Rotativa which is available as a Nuget. It does what we need. We've been using it in production for 9 months without any issues.
