### ISSUE TITLE
The document has no pages

### ISSUE THREAD

**Issue by VagueGit** [DesignLiquido/RazorPDF2#2]
[IOException: The document has no pages.]
   iTextSharp.text.pdf.PdfPages.WritePageTree() +1040
   iTextSharp.text.pdf.PdfWriter.Close() +285
   iTextSharp.text.pdf.PdfDocument.Close() +318
   iTextSharp.text.Document.Close() +110
   iTextSharp.text.Document.Dispose() +29
   RazorPDF.RazorToPdf.GeneratePdfOutput(ControllerContext context, Object model, String viewName, Action`2 configureSettings) +631
   RazorPDF.RazorToPdfExtensions.GeneratePdf(ControllerContext context, Object model, String viewName, Action`2 configureSettings) +91
   RazorPDF.PdfActionResult.ExecuteResult(ControllerContext context) +704
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) +13
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +56
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +420
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +52
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +173
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9744373
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1073.0

Using Visual Studio 2015 targeting Asp.NET 4.5.2 calling PdfActionResult with a valid model.

**Comment by joshgarwood** [comment]
EDIT:  I adjusted my view so it did not use the default `Layout` and this fixed my issue.  Sorry for the confusion!

I'm having this issue as well @cigano... Is this a known issue, or is there a chance I've misconfigured something in my project?

Thanks!

**Comment by VagueGit** [comment]
I didn't get any response to this issue so I switched to Rotativa.

**Comment by cigano** [comment]
@VagueGit This error normally happens when iTextSharp raises an error.

Prefer to use `PdfActionResult` instead of `PdfResult` to render your Views.
