### ISSUE TITLE
About the Licence

### ISSUE THREAD

**Issue by Jedarc** [DesignLiquido/RazorPDF2#3]
Dear friend, I want to develop web software for use in an educational network (where I work), but I do not know if it is possible to use your library per legal reasons.
I was a bit confused because in `readme.md` the license is **MIT**, in `license.txt` the license is **Apache v2.0**, but the project uses as dependency the iTextSharp that has an **LGPLv2** license.
Note: I can not leave my code open.

[pt-br]
Querido amigo, estou querendo desenvolver um software web para uso em uma rede educacional na qual trabalho, mas não sei exatamente se posso utilizar sua biblioteca por questões legais.
Fiquei um pouco confuso, pois em `Readme.md` a licença é **MIT**, em `License.txt` a licença é **Apache v2.0**, mas o projeto usa como dependência o iTextSharp que tem a licença **LGPLv2**.
Obs: não posso deixar meu código aberto.

**Comment by cigano** [comment]
Jedaias,

Não sendo uma aplicação comercial, pode usar sem problemas. Como seu
software possivelmente é de apoio ao serviço educacional (ou seja, você não
está vendendo o software diretamente), não creio que a iText irá demandar
uma licença comercial.

2017-03-03 8:00 GMT-06:00 Jedaias Rodrigues <notifications@github.com>:
